### ISSUE TITLE
Error: Cannot find module 'Hapi'

### ISSUE THREAD

**Issue by dsdenes** [diasdavid/webrtc-explorer#7]
$ git clone git@github.com:diasdavid/webrtc-explorer-signalling-server.git
$ cd webrtc-explorer-signalling-server/
$ npm install
$ npm start

Error: Cannot find module 'Hapi'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/ds/webrtc-explorer-signalling-server/src/index.js:1:74)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)

$ node -v
v2.3.1 (iojs)

System:
Ubuntu 14.04

**Comment by diasdavid** [comment]
That's very strange. Can you check if it was installed on the node_modules folder? The dependency is there: https://github.com/diasdavid/webrtc-explorer-signalling-server/blob/master/package.json#L9

I've also haven't tried any iojs with this. There is also a iojs@3.0.0 now and soon there will be node@4.0.0, once that is released, I intend going to all my modules and updating all the dependencies, making sure it works with latest
